# Generated by Django 3.2.4 on 2021-07-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatroom_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(fields=('name', 'creator'), name='unique_name_and_creator'),
        ),
    ]
