# Generated by Django 3.2.4 on 2021-07-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20210709_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitelink',
            name='user',
        ),
        migrations.AddField(
            model_name='invitelink',
            name='email',
            field=models.EmailField(default='immanuelcaspian@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
