# Generated by Django 3.2.4 on 2021-07-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20210709_1137'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invitelink',
            constraint=models.UniqueConstraint(fields=('chatroom', 'email'), name='unique_email_and_chatroom'),
        ),
    ]
