# Generated by Django 3.2.4 on 2021-07-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_invitelink_unique_email_and_chatroom'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatroommember',
            constraint=models.UniqueConstraint(fields=('chatroom', 'user'), name='unique_user_and_chatroom'),
        ),
    ]
