# Generated by Django 3.2.4 on 2021-07-20 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0013_chatroommessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroommember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chatroom_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
